---
- name: Execute local script on server
  hosts: localhost
  #become: yes

  tasks:
    - name: Execute bash script
      ansible.builtin.scripts: getIP.sh
      register: output

    - debug:
        msg: "{{ output.stdout }}"

